apiVersion: v1
kind: Service
metadata:
  name: static-site
  namespace: web
spec:
  type: LoadBalancer
  selector:
    app: static-site
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP