apiVersion: v1
kind: Service
metadata:
  name: static-site
  namespace: web
spec:
  type: NodePort
  selector:
    app: static-site
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080   # optional; omit to let K8s choose in 30000–32767